version: "3.7"

services: 
    database:
      image: mongo:latest
      ports:
        - 207017:207017
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD

      volumes:
        - ${HOME}/docker/volumes/mongo:/data/db
    smtp:
      build: https://github.com/mailhog/MailHog.git#master
      ports:
        - 8025:8025
    
    ecommerce:
      depends_on: 
        - smtp
        - database
      build: https://github.com/riuGlobal/cezerin2.git#feature/dockerfile
      ports:
        - 3006:3001
      environment:
        - SMTP_HOST
        - SMTP_PORT
        - SMTP_SECURE
        - DB_HOST
        - DB_PORT
        - DB_NAME
        - DB_USER
        - DB_PASS
        - FRONT_URL=http://localhost:3012

    web:
      depends_on:
        - ecommerce
      ports: 
        - ${PORT:3012}:3000
      build: https://github.com/riuGlobal/cezerin-web-example.git#feature/configs-dockerfile
      environment:
        # - CLIENT_URL=http://localhost:3006
        # - SERVER_URL=http://ecommerce:3001
        - REACT_APP_CLIENT_URL=http://192.168.0.33:3006
        - REACT_APP_SERVER_URL=http://ecommerce:3001
    ## notifier

    ## loyalty

