services: 
  database:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

    volumes:
      - ${HOME}/docker/volumes/mongo:/data/db

  ecommerce:
    depends_on:
      - database
  
