version: "3.7"

services: 
    web:
      build: https://riu.global@github.com/riuGLobal
    ecommerce:
      build: https://riu.global@github.com/riuGLobal

    ## smtp
    
    ## notifier

    ## loyalty

