version: "3.8"

services: 

  loyalty-cards-admin:
    build: https://github.com/riuGlobal/loyalty-cards-admin.git#${LOYALTY_CARDS_ADMIN_VERSION:-master}
    ports:
      - 3003:3000
    environment:
      - ESLINT_NO_DEV_ERRORS
      - REACT_APP_LOYALTY_CARDS_API_HOST=${LOYALTY_CARDS_API_HOST}
  loyalty-cards-web:
    build: https://github.com/riuGlobal/loyalty-cards-web.git#${LOYALTY_CARDS_WEB_VERSION:-master}
    ports:
      - 3002:3000
    environment:
      - REACT_APP_LOYALTY_CARDS_API_HOST=${LOYALTY_CARDS_API_HOST}
  loyalty-cards:
    build: https://github.com/riuGlobal/loyalty-cards.git#${LOYALTY_CARDS_VERSION:-master}
    ports:
      - 8030:8000
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=${PG_DB_HOST}
      - TYPEORM_PORT=${PG_DB_PORT}
      - TYPEORM_USERNAME=${PG_DB_USER}
      - TYPEORM_PASSWORD=${PG_DB_PASSWORD}
      - TYPEORM_DATABASE=${LOYALTY_CARDS_PG_DB_DATABASE}
      - TYPEORM_SCHEMA=${LOYALTY_CARDS_PG_DB_SCHEMA}
      - TYPEORM_SYNCHRONIZE=${LOYALTY_CARDS_PG_DB_SYNC}
      - TYPEORM_ENTITIES=dist/**/*.entity.js

  # loyalty-cards-web:
  #   build

  loyalty-cards-cezerin-middleware:
    build: https://github.com/riuGlobal/loyalty-cards-cezerin-middleware.git#${LOYALTY_CARDS_CEZERIN_MW_VERSION:-master}
    ports:
      - 8031:8000
    environment:
      - LOYALTY_CARDS_HOST=${LOYALTY_CARDS_API_HOST:-http://loyalty-cards:8030}
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=${PG_DB_HOST}
      - TYPEORM_PORT=${PG_DB_PORT}
      - TYPEORM_USERNAME=${PG_DB_USER}
      - TYPEORM_PASSWORD=${PG_DB_PASSWORD}
      - TYPEORM_DATABASE=${LOYALTY_CARDS_CEZERIN_MW_PG_DB_DATABASE}
      - TYPEORM_SCHEMA=${LOYALTY_CARDS_CEZERIN_MW_PG_DB_SCHEMA}
      - TYPEORM_SYNCHRONIZE=${LOYALTY_CARDS_CEZERIN_MW_PG_DB_SYNC}
      - TYPEORM_ENTITIES=dist/**/*.entity.js
    depends_on:
      - loyalty-cards
  smtp:
    build: https://github.com/mailhog/MailHog.git#master
    ports:
      - 8025:8025
  
  ecommerce:
    depends_on: 
      - smtp
      # - database
    build: https://github.com/riuGlobal/cezerin2.git#${ECOMMERCE_BRANCH:-master}
    ports:
      - 8016:3001
      - 8017:3000
    environment:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASS
      - FRONT_URL=${FRONT_URL_CORS:-http://localhost:3000}

  web:
    depends_on:
      - ecommerce
    ports: 
      - "${WEB_PORT:-3000}:3000"
    build: https://github.com/riuGlobal/cezerin-web-example.git#${WEB_BRANCH:-master}
    environment:
      - REACT_APP_SERVER_URL=http://ecommerce:3001
      - REACT_APP_CLIENT_URL=${WEB_CLIENT_URL}
      - REACT_APP_LOYALTY_URL

  admin:
    depends_on: 
      - ecommerce
    ports: 
      - "${ADMIN_PORT:-3001}:3000"
    build: https://github.com/riuGlobal/cezerin-admin.git#${ADMIN_BRANCH:-master}
    environment:
      - REACT_APP_CLIENT_URL=${ADMIN_CLIENT_URL}
      - REACT_APP_WEB_SOCKET=${ADMIN_WEB_SOCKET}

      
  ## notifier

  ## loyalty

